config/routes.rb
Micropost::Application.routes.draw do
  get "home/index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/faq"
  get "static_pages/services"
  get "static_pages/blog"
  get "static_pages/blog_post"

  namespace :admin do
    resources :pets

  end

   namespace :admin do
    resources :institutions
  end

  namespace :admin do
    resources :posts
  end

  resources :pets

  resources :institutions

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :posts

  resources :users
  root 'home#index'

  get 'tags/:tag', to: 'pets#index', as: :tag
    resources :pets do
     collection do
     get :search

    end   
 end

resources :pet do
  collection do
    match 'search' => 'pet#search', via: [:get, :post], as: :search
  end
end

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def comming
    end

    def about
    end

    def contact
    end

    def faq
    end

    def services
    end

	  

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comming %><br>
    <%= f.text_field :comming %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<!-- Main -->
		<div class="main" role="main">

			<!-- Page Heading -->
			<section class="page-heading">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<h1>¿Quiénes somos?</h1>
						</div>
						<div class="col-md-6">
							<ul class="breadcrumb">
								<li><a href="/">Inicio</a></li>
								<li><a href="faq">Preguntas Frecuentes</a></li>
								<li class="active">¿Quiénes Somos?</li>
							</ul>
						</div>
					</div>
				</div>
			</section>
			<!-- Page Heading / End -->

			<!-- Page Content -->
			<section class="page-content">
				<div class="container">
					
					<div class="row">
						<div class="col-md-6">
							<figure class="alignnone">
								<%= image_tag("logo-adoptameV2_558px.png")%>
							</figure>
						</div>
						<div class="col-md-6">
							<h2>Bienvenido a Adopta-Me!</h2>
							<p> Adopta-me es una base de datos en línea que permite la búsqueda de mascotas sin hogar disponibles para adopción en Colombia. </p>

							<p> Facilita al usuario la búsqueda de mascotas en adopción a nivel nacional. Permite a las fundaciones difundir de manera más amplia y ágil las mascotas para adopción, de manera a incrementar la cantidad de adopciones en el país de manera responsable y eficaz.</p> 

							<div class="spacer-sm"></div>
							
							<a href="/static_pages/contact" class="btn btn-success">Contáctanos</a>
						</div>
					</div>

					<div class="section-light">
						<div class="row">
							<div class="col-md-6">
								<h2>¿Por qué vincularse con nosotros?</h2>
								<div class="panel-group panel-group__alt" id="accordion">
									<div class="panel panel-default">
										<div class="panel-heading">
											<h4 class="panel-title">
												<a data-toggle="collapse" data-parent="#accordion" href="#accordion-1">
													Manejamos una amplia base de datos en el país
												</a>
											</h4>
										</div>
										<div id="accordion-1" class="panel-collapse collapse in">
											<div class="panel-body">
												<p>Ser parte de la red de Fundaciones de Adopta-Me, le permite una mayor difusión de sus mascotas a nivel nacional, de manera a llegar a más usuarios que buscan brindar un hogar cálido y responsable a las mascotas.</p>

												Ser usuario de Adopta-Me le proporciona como usuario una amplia variedad de mascotas a escoger para hacer parte de su hogar.
											</div>
										</div>
									</div>
									<div class="panel panel-default">
										<div class="panel-heading">
											<h4 class="panel-title">
												<a data-toggle="collapse" data-parent="#accordion" href="#accordion-2" class="collapsed">
													Confiabilidad, seguridad y seriedad
												</a>
											</h4>
										</div>
										<div id="accordion-2" class="panel-collapse collapse">
											<div class="panel-body">
												<p> Somos una Fundación Sin Ánimo de Lucro, como tal buscamos lograr incrementar las cifras de adopción responsable de mascotas en el país. Por lo cual, por medio de una selección cuidadosa y reglamentada, hacemos el filtro de las fundaciones que cumplan a cabalidad los requisitos requeridos para brindar tanto al usuario y a otras fundaciones, la confiabilidad, credibilidad y seguridad para ser parte de la comunidad Adopta-Me. </p>

												
											</div>
										</div>
									</div>
									<div class="panel panel-default">
										<div class="panel-heading">
											<h4 class="panel-title">
												<a data-toggle="collapse" data-parent="#accordion" href="#accordion-3" class="collapsed">
													Promovemos la adopción responsable
												</a>
											</h4>
										</div>
										<div id="accordion-3" class="panel-collapse collapse">
											<div class="panel-body">
												<p> Promover la adopción responsable como el lema principal de Adopta-Me. Concientizar al usuario que una mascota no es un juguete, sino que es un ser vivo que merece todo el cuidado, respeto y amor que podamos darle.</p>

												
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="spacer-lg visible-sm visible-xs"></div>
								<h2>Nuestras Capacidades</h2>
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
										<span class="progress-label">Confiabilidad</span>
										100%
									</div>
								</div>
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
										<span class="progress-label">Seguridad &amp; Seriedad</span>
										100%
									</div>
								</div>
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
										<span class="progress-label">Difusión</span>
										100%
									</div>
								</div>
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
										<span class="progress-label">Variedad de mascotas</span>
										100%
									</div>
								</div>
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
										<span class="progress-label">Compromiso con el usuario y las mascotas</span>
										100%
									</div>
								</div>
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
										<span class="progress-label">Disponibilidad 24 / 7</span>
										100%
									</div>
								</div>
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
										<span class="progress-label">Cobertura Nacional</span>
										100%
									</div>
								</div>
							</div>
						</div>
					</div>


					<h2>Nuestro Equipo</h2>
					<ul class="team-list row">
						<li class="team-item col-md-3">
							<!-- <div class="team-item-inner">
								<figure class="team-thumb">
									<img src="http://placehold.it/288x268" alt="">
								
									<div class="overlay"></div>
								
									<ul class="team-social list-unstyled">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
									</ul>
								
								</figure>
								<header class="team-head">
									<h5 class="team-name">John Doe</h5>
									<span class="team-head-info">CEO</span>
								</header>
								<div class="team-excerpt">
									Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem
									Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem
								</div>
							</div> -->
						</li>
						<li class="team-item col-md-3">
							<div class="team-item-inner">
								<figure class="team-thumb">
									<%= image_tag("mcr288x268.png") %>
								
									<div class="overlay"></div>
								
									<ul class="team-social list-unstyled">
										<!-- <li><a href="#"><i class="fa fa-facebook"></i></a></li> -->
										<li><a href="https://twitter.com/Adoptame_co"><i class="fa fa-twitter"></i></a></li>
										<!-- <li><a href="#"><i class="fa fa-google-plus"></i></a></li> -->
									</ul>
								
								</figure>
								<header class="team-head">
									<h5 class="team-name">María Camila Ruiz Abondano</h5>
									<span class="team-head-info">Fundadora</span>
								</header>
								<div class="team-excerpt">
									Fundadora de Adopta-Me, dueña y amante de las mascotas.
								</div>
							</div>
						</li>
						<li class="team-item col-md-3">
							<div class="team-item-inner">
								<figure class="team-thumb">
									<%= image_tag("diegoleon_288x268.png") %>
								
									<div class="overlay"></div>
								
									<ul class="team-social list-unstyled">
										<!-- <li><a href="#"><i class="fa fa-facebook"></i></a></li> -->
										<li><a href="https://twitter.com/Adoptame_co"><i class="fa fa-twitter"></i></a></li>
										<!-- <li><a href="#"><i class="fa fa-google-plus"></i></a></li> -->
									</ul>
								
								</figure>
								<header class="team-head">
									<h5 class="team-name">Diego León</h5>
									<span class="team-head-info">Co-Fundador</span>
								</header>
								<div class="team-excerpt">
									Fundador de iPet Chicago, dueño y amante de las mascotas.
								</div>
							</div>
						</li>
						<li class="team-item col-md-3">
							<!-- <div class="team-item-inner">
								<figure class="team-thumb">
									<img src="http://placehold.it/288x268" alt="">
								
									<div class="overlay"></div>
								
									<ul class="team-social list-unstyled">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
									</ul>
								
								</figure>
								<header class="team-head">
									<h5 class="team-name">Hanna Doe</h5>
									<span class="team-head-info">HTML Coder</span>
								</header>
								<div class="team-excerpt">
									Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem
									Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem
								</div>
							</div> -->
						</li>
					</ul>

					<hr class="lg">

					<h2>Colaboradores</h2>
					<div class="row">
						<div class="col-sm-3 col-md-3">
							<div class="text-center">
								<a href="http://worldtechmakers.com/#impact-2" target="_blank"><%=image_tag("wtm_logo-300x300.png")%> <alt="" class="img-responsive"></a>
							</div>
						</div>
						<div class="col-sm-3 col-md-3">
							<div class="text-center">
								<a href="http://ipetchicago.com/" target="_blank"><%=image_tag("ipetchicago-logo300x300.png")%> <alt="" class="img-responsive"></a>
							</div>
						</div>
						<div class="col-sm-3 col-md-3">
							<div class="text-center">
								<a href="http://www.tarefa.co/" target="_blank"><%=image_tag("tarefa-logo-300x300.png")%> <alt="" class="img-responsive"></a>
							</div>
						</div>
					<!-- 	<div class="col-sm-3 col-md-3">
							<div class="text-center">
								<a href="#"><%=image_tag("fundacion-zoomima-270.png")%> <alt="" class="img-responsive"></a>
							</div>
						</div> -->
					</div>

				</div>
			</section>
			<!-- Page Content / End -->

app/views/static_pages/comming.html.erb
	<div class="main main__padd-top" role="main">

			<!-- Page Content -->
			<section class="page-content">
				<div class="container">

					<div class="row">
						<div class="col-md-8 col-md-offset-2 text-center">
							<h1>Our Site is launching soon...</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis congue eros. Quisque sagittis volutpat metus nec tristique. Justo, id egestas ligula fringilla interdum. Suspendisse id justo non nibh volutpat faucibus et vel justo.</p>
						</div>
					</div>

					<div id="countdown" class="countdown text-center">
						<div class="row">
							<div class="col-sm-3 col-md-3 col-lg-offset-2 col-lg-2 text-center">
								<input class="knob" id="days" data-readonly=true data-min="0" data-max="99" data-skin="tron" data-width="165" data-height="165" data-thickness="0.2" data-fgcolor="#a6ce39">
								<span class="count-label">days</span>
							</div>
							
							<div class="col-sm-3 col-md-3 col-lg-2">
								<input class="knob" id="hours" data-readonly=true data-min="0" data-max="24" data-skin="tron" data-width="165" data-height="165" data-thickness="0.2" data-fgcolor="#a6ce39">
								<span class="count-label">hours</span>
							</div>
							
							<div class="col-sm-3 col-md-3 col-lg-2">
								<input class="knob" id="mins" data-readonly=true data-min="0" data-max="60" data-skin="tron" data-width="165" data-height="165" data-thickness="0.2" data-fgcolor="#a6ce39">
								<span class="count-label">minutes</span>
							</div>
							
							<div class="col-sm-3 col-md-3 col-lg-2">
								<input class="knob" id="secs" data-readonly=true data-min="0" data-max="60" data-skin="tron" data-width="165" data-height="165" data-thickness="0.2" data-fgcolor="#a6ce39">
								<span class="count-label">seconds</span>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-8 col-md-offset-2">
							<hr class="lg">
						</div>
					</div>

					<div class="row">
						<div class="col-md-4 col-md-offset-4">
							<form action="#" class="newsletter-form">
								<div class="input-group">
									<input type="text" class="form-control" placeholder="Enter your email here">
									<span class="input-group-btn">
										<button class="btn btn-success" type="button"><i class="fa fa-arrow-circle-o-right"></i></button>
									</span>
								</div>
							</form>
						</div>
					</div>

				</div>
			</section>
			<!-- Page Content / End -->

app/views/static_pages/contact.html.erb
<!-- Main -->
		<div class="main" role="main">

			<!-- Page Heading -->
			<section class="page-heading">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<h1>Contáctenos</h1>
						</div>
						<div class="col-md-6">
							<ul class="breadcrumb">
								<li><a href="/">Inicio</a></li>
								<li class="active">Contáctenos</li>
							</ul>
						</div>
					</div>
				</div>
			</section>
			<!-- Page Heading / End -->

			<!-- Page Content -->
			<section class="page-content">

				<div class="container">

					<!-- Google Map -->
					<div class="googlemap-wrapper">
						<div id="map_canvas" class="map-canvas">
								<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1018540.5022863325!2d-74.22404!3d4.283435!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3f9bfd2da6cb29%3A0x239d635520a33914!2sBogot%C3%A1%2C+Colombia!5e0!3m2!1ses!2ses!4v1412302574043" width="1126" height="390" frameborder="0" style="border:0"></iframe>
						</div>
					</div>
<!-- Google Map / End -->
					
					
<!-- <body id="public"> -->
<div class="col-md-9">
		


		<form id="form1" name="form1" class="wufoo topLabel page" accept-charset="UTF-8" autocomplete="off" enctype="multipart/form-data" method="post" novalidate
			      action="https://mumiruiz.wufoo.com.mx/forms/z1go54cf1lb941t/#public">
			  
			<header id="header" class="info">
			<h1>Contáctenos</h1>
			<div><h2>¿Tiene alguna inquietud, duda o sugerencia? ¡Escríbanos!</h2></div>
			</header>
<!-- NAME  -->
			<ul>
			  <h3>	
				<li id="foli13" class="notranslate      ">
				<label class="desc" id="title13" for="Field13">
				Nombre
				<span id="req_13" class="req">*</span>
				</label>
				<div>
				<input id="Field13" name="Field13" type="text" class="field text medium" value="" maxlength="200" tabindex="1" onkeyup="validateRange(13, 'character');"       required />
				<label for="Field13"><var id="rangeMaxMsg13"></var><em class="currently"><var id="rangeUsedMsg13"></var></em></label>
				</div>
				</li>
			</br>
<!-- END NAME  -->

<!-- EMAIL  -->

				<li id="foli3" class="notranslate      ">
				<label class="desc" id="title3" for="Field3">
				Correo electrónico
				<span id="req_3" class="req">*</span>
				</label>
				<div>
				<input id="Field3" name="Field3" type="email" spellcheck="false" class="field text medium" value="" maxlength="255" tabindex="2"       required />
				</div>
				</li>
			</br>

<!-- END EMAIL  -->

<!-- MESSAGE  -->
				<li id="foli5"
				class="notranslate      "><label class="desc" id="title5" for="Field5">
				Mensaje
				<span id="req_5" class="req">*</span>
				</label>

				<div>
				<textarea id="Field5"
				name="Field5"
				class="field textarea medium"
				spellcheck="true"
				rows="10" cols="50"

				tabindex="3"
				onkeyup=""
				      required  ></textarea>

				</div>
			</br>
<!-- END MESSAGE  -->

<!-- SEND BUTTON  -->
				</li> <li class="buttons">
				<div>

				                    <input id="saveForm" name="saveForm" class="btTxt submit"
				    type="submit" value="Enviar"
				 /></div>
				</li>
				<li class="hide">
				<label for="comment">Do Not Fill This Out</label>
				<textarea name="comment" id="comment" rows="1" cols="1"></textarea>
				<input type="hidden" id="idstamp" name="idstamp" value="9yZ6O02oRduvhztnwvk6L7nn7jEP3yIh+by2foEAMrE=" />
				</li>
			   </h2>	
			</ul>
		</form>
<!-- END SEND BUTTON  -->	 

		<!--container-->

		<a class="powertiny" href="http://www.adoptame.co/" title="Adopta-Me"
		style="display:block !important;visibility:visible !important;text-indent:0 !important;position:relative !important;height:auto !important;width:95px !important;overflow:visible !important;text-decoration:none;cursor:pointer !important;margin:0 auto !important">
		<span style="background:url(assets/logo.png) no-repeat center 7px; margin:0 auto;display:inline-block !important;visibility:visible !important;text-indent:-9000px !important;position:static !important;overflow: auto !important;width:62px !important;height:30px !important"></span>
		<b style="display:block !important;visibility:visible !important;text-indent:0 !important;position:static !important;height:auto !important;width:auto !important;overflow: auto !important;font-weight:normal;font-size:9px;color:#777;padding:0 0 0 3px;"></b>
		</a>

</div>





<!-- Widget :: Contacts Info -->
							<div class="contacts-widget widget widget__sidebar">
								<h2 class="widget-title">Búsquenos también en:</h2>

								</br>
								</br>

								<div class="widget-content">
									<ul class="contacts-info-list">
										<li>
											<i class="fa fa-map-marker"></i>
											<div class="info-item">
												Fundación Adopta-Me,</br>
												Bogotá - Colombia.
											</div>
										</li>
										<li>
											<i class="fa fa-envelope"></i>
											<span class="info-item">
												<a href="mailto:info@adoptame.co">info@adoptame.co</a>
											</span>
										</li>
										<li>
											<i class="fa fa-facebook"></i>
											<div class="info-item">
												<a href="www.facebook.com/AdoptaMeColombia">AdoptaMeColombia</a><br>
												
											</div>
										</li>
										<li>
											<i class="fa fa-twitter"></i>
											<div class="info-item">
												<a href="https://twitter.com/Adoptame_co">@Adoptame_co</a><br>
												
											</div>
										</li>
										<li>
											<i class="fa fa-clock-o"></i>
											<div class="info-item">
												24 horas
											</div>
										</li>
									</ul>
								</div>
							</div>
							<!-- /Widget :: Contacts Info -->
						</div>
					</div>

				</div>

			</section>
			<!-- Page Content / End -->

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <thead>
    <tr>
      <th>Comming</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= static_page.comming %></td>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comming:</strong>
  <%= @static_page.comming %>
</p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>

<!-- Correction -->