config/routes.rb
Micropost::Application.routes.draw do
  get "home/index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/faq"
  get "static_pages/services"
  get "static_pages/blog"
  get "static_pages/blog_post"

  namespace :admin do
    resources :pets

  end

   namespace :admin do
    resources :institutions
  end

  namespace :admin do
    resources :posts
  end

  resources :pets

  resources :institutions

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :posts

  resources :users
  root 'home#index'

  get 'tags/:tag', to: 'pets#index', as: :tag
    resources :pets do
     collection do
     get :search

    end   
 end

resources :pet do
  collection do
    match 'search' => 'pet#search', via: [:get, :post], as: :search
  end
end

end

app/models/institution.rb
class Institution < ActiveRecord::Base
has_attached_file :logo, :styles => { :large => "708x671#", :medium => "470x470#", :thumb => "58x58xs#" },
                  :storage => :s3,
                  :bucket => 'adoptame-pets-photos'

  validates_attachment_content_type :logo, :presence => true, :size => { :in => 0..10.megabytes }, :content_type => /\Aimage\/.*\Z/
	acts_as_taggable

has_many :pets
accepts_nested_attributes_for :pets
	end

app/controllers/admin/institutions_controller.rb
class Admin::InstitutionsController < ApplicationController
  before_action :set_admin_institution, only: [:show, :edit, :update, :destroy]
  #before_action :authorize_user

  # GET /admin/institutions
  # GET /admin/institutions.json
  def index
    @admin_institutions = Institution.all
  end

  # GET /admin/institutions/1
  # GET /admin/institutions/1.json
  def show
  end

  # GET /admin/institutions/new
  def new
    @admin_institution = Institution.new
  end

  # GET /admin/institutions/1/edit
  def edit
  end

  # POST /admin/institutions
  # POST /admin/institutions.json
  def create
    @admin_institution = Institution.new(admin_institution_params)

    respond_to do |format|
      if @admin_institution.save
        format.html { redirect_to @admin_institution, notice: 'Institution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_institution }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/institutions/1
  # PATCH/PUT /admin/institutions/1.json
  def update
    respond_to do |format|
      if @admin_institution.update(admin_institution_params)
        format.html { redirect_to @admin_institution, notice: 'Institution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/institutions/1
  # DELETE /admin/institutions/1.json
  def destroy
    @admin_institution.destroy
    respond_to do |format|
      format.html { redirect_to admin_institutions_url }
      format.json { head :no_content }
    end
  end

  private

    #Hide admin view for users and redirect to public path
   # def authorize_user
    
   #    if current_user.nil?
   #      redirect_to home_index_path 
   #    else
   #      redirect_to institutions_path  
   #    end
   #  end

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_institution
      @admin_institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_institution_params
      params.require(:admin_institution).permit(:name, :username, :email, :password, :manager, :country, :region, :city, :website, :logo, :tag_list)
    end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
 
  

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
    @pets = Institution.all.limit(3)
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @admin_institution, notice: 'Institution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_institution }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @admin_institution, notice: 'Institution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to admin_institutions_url }
      format.json { head :no_content }
    end
  end

  def preview
  @logo = Intitution_logo.find(params[:id])
   if @logo.contenttype == "image"          
      img_orig = Magick::Image.read("/assets/images/"+@photo.filename).first
      img = img_orig.resize_to_fit(200,200)
     @response.headers["Content-type"] = img.mime_type
      render :text => img.to_blob    
   end
end

  private


   

    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :username, :email, :password, :location, :website,:country,:region, :city, :logo, :manager, :description, :tag_list)
    end
end

app/helpers/admin/institutions_helper.rb
module Admin::InstitutionsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/admin/institutions/_form.html.erb
<%= form_for(@admin_institution) do |f| %>
  <% if @admin_institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_institution.errors.count, "error") %> Prohibido crear la el Administrador de Insituciones</h2>

      <ul>
      <% @admin_institution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :username, "Usuario" %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %><br>
    <input type="email" name="email">
  </div>
  <div class="field">
    <%= f.label :password, "Contraseña" %><br>
    <%= f.text_field :password %>
  </div>

 <div class="field">
    <%= f.label :manager, "Representante Legal" %><br>
    <%= f.text_field :manager %>
  </div>  

  <div class="field">
    <%= f.label :website, "Sitio Web" %><br>
    <input type="url" name="homepage">
  </div>

  <div class="field">
    <%= f.label :description, "Descripción" %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
  <%= f.label :logo %><br />
  <%= f.file_field :logo %>
</div>
  
   <div class="field">
    <%= f.label :country, "País" %><br>
    <select name="institution[country]">
    <option value = "Colombia">Colombia</option>
   </select>
  </div>
<br>

  <div class="field">
    <%= f.label :region, "Región" %><br>
    <select name="institution[region]">
      <option value = "Amazonas">Amazonas</option>
      <option value = "Antioquia">Antioquia</option>
      <option value = "Arauca">Arauca</option>
      <option value = "Atlántico">Atlántico</option>
      <option value = "Bolívar">Bolívar</option>
      <option value = "Boyacá">Boyacá</option>
      <option value = "Caldas">Caldas</option>
      <option value = "Caquetá">Caquetá</option>
      <option value = "Casanare">Casanare</option>
      <option value = "Cauca">Cauca</option>
      <option value = "Cesar">Cesar</option>
      <option value = "Chocó">Chocó</option>
      <option value = "Córdoba">Córdoba</option>
      <option value = "Cundinamarca">Cundinamarca</option>
      <option value = "Guainía">Guainía</option>
      <option value = "Guaviare">Guaviare</option>
      <option value = "Huila">Huila</option>
      <option value = "La Guajira">La Guajira</option>
      <option value = "Magdalena">Magdalena</option>
      <option value = "Meta">Meta</option>
      <option value = "Nariño">Nariño</option>
      <option value = "Norte de Santander">Norte de Santander</option>
      <option value = "Putumayo">Putumayo</option>
      <option value = "Quindío">Quindío</option>
      <option value = "Risaralda">Risaralda</option>
      <option value = "San Andrés y Providencia">San Andrés y Providencia</option>
      <option value = "Santander">Santander</option>
      <option value = "Sucre">Sucre</option>
      <option value = "Tolima">Tolima</option>
      <option value = "Valle del Cauca">Valle del Cauca</option>
      <option value = "Vaupés">Vaupés</option>
      <option value = "Vichada">Vichada</option>
    </select>
  </div>
  <br>

  <div class="field">
    <%= f.label :city, "Ciudad" %><br>
    <select name="institution[city]">
      <option value = "Arauca">Arauca</option>
      <option value = "Armenia">Armenia</option>
      <option value = "Barranquilla">Barranquilla</option>
      <option value = "Bogotá">Bogotá</option>
      <option value = "Bucaramanga">Bucaramanga</option>
      <option value = "Cali">Cali</option>
      <option value = "Cartagena de Indias">Cartagena de Indias</option>
      <option value = "Cucutá">Cucutá</option>
      <option value = "Florencia">Florencia</option>
      <option value = "Ibagué">Ibagué</option>
      <option value = "Inírida">Inírida</option>
      <option value = "Leticia">Leticia</option>
      <option value = "Manizalez">Manizalez</option>
      <option value = "Medellín">Medellín</option>
      <option value = "Mitú">Mitú</option>
      <option value = "Mocoa">Mocoa</option>
      <option value = "Montería">Montería</option>
      <option value = "Neiva">Neiva</option>
      <option value = "Pasto">Pasto</option>
      <option value = "Pereira">Pereira</option>
      <option value = "Popayán">Popayán</option>
      <option value = "Puerto Carreño">Puerto Carreño</option>
      <option value = "Quibdó">Quibdó</option>
      <option value = "Riohacha">Riohacha</option>
      <option value = "San Andrés">San Andrés</option>
      <option value = "San José del Guaviare">San José del Guaviare</option>
      <option value = "Santa Marta">Santa Marta</option>
      <option value = "Sincelejo">Sincelejo</option>
      <option value = "Tunja">Tunja</option>
      <option value = "Valledupar">Valledupar</option>
      <option value = "Villavicencio">Villavicencio</option>
      <option value = "Yopal">Yopal</option>
    </select>
  </div>
<br />

</div>
  <div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>
<br />
  <div class="actions">
    <%= f.submit "Crear Institución" %>
  </div>
<% end %>

app/views/admin/institutions/edit.html.erb
<h1>Administrador de Instituciones</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @admin_institution %> |
<%= link_to 'Atrás', admin_institutions_path %>

app/views/admin/institutions/index.html.erb
<div class="main" role="main">

      <!-- Page Heading -->
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h1>Administrador de  Mascotas</h1>
            </div>
                <div class="col-md-6">
                   <ul class="breadcrumb">
                      <li><a href="/">Inicio</a></li>
                      <li><a href="about">¿Quiénes Somos?</a></li>
                      <li class="active">Adminitrador de Mascotas</li>
                   </ul>
                </div>
             </div>
        </div>
      </section>
      <!-- Page Heading / End -->

          <!-- Page Content -->
      <section class="page-content">
        <div class="container">

            <div class="table-responsive">
              <table class="job-manager-jobs table table-bordered table-striped">
                <thead>
                  <tr>
                      <th>Nombre</th>
                      <th>Usuario</th>
                      <th>Email</th>
                      <th>Contraseña</th>
                      <th>Representante Legal</th>
                      <th>País</th>
                      <th>Región</th>
                      <th>Ciudad</th>
                      <th>Descripción</th>
                      <th>Sitio Web</th>
                      <th>Tags</th>

                  </tr>
                </thead>
      <tbody>
    <% @admin_institutions.each do |admin_institution| %>
      <tr>
        <td><%= admin_institution.name %></td>
        <td><%= admin_institution.username %></td>
        <td><%= admin_institution.email %></td>
        <td><%= admin_institution.password %></td>
        <td><%= admin_institution.manager %></td>
        <td><%= admin_institution.country %></td>
        <td><%= admin_institution.region %></td>
        <td><%= admin_institution.city %></td>
        <td><%= admin_institution.description %></td>
        <td><%= admin_institution.website %></td>
        <td><%= admin_institution.tag_list%></td>

        <td><%= link_to 'Mostrar', admin_institution %></td>
        <td><%= link_to 'Editar', edit_admin_institution_path(admin_institution) %></td>
        <td><%= link_to 'Eliminar', admin_institution, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
              </table>

              
<%= link_to 'Nueva Institución', new_admin_institution_path %>
            </div>

          </div>

        </div>
      </section>

app/views/admin/institutions/new.html.erb
<!-- Page Heading -->
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
            <h1>Nueva Institución</h1>
            </div>
            <div class="col-md-6">
              <ul class="breadcrumb">
                <li><a href="index.html">Inicio</a></li>
                <li><a href="#">Mascotas</a></li>
                <li class="active">Ingresar nueva Mascota</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
<!-- Page Heading / End -->


<section class="page-content">
        <div class="container">
          
          <div class="row">
            <div class="col-md-8 col-md-offset-2">

  

<%= form_for(@admin_institution) do |f| %>
  <% if @admin_institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% @admin_institution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
              <fieldset>
                <label>Logo<span class="required">*</span></label>
                 <div>
                <%= f.file_field :logo %>
                </div>
              </fieldset>
               <br /> 
  
        <fieldset>
                  <label>Nombre <span class="required">*</span></label>
                  <div>
                   <%= f.text_field :name, class: "form-control"%>
                  </div>
                </fieldset>
                <br />
                 <fieldset>
                  <label>Usuario <span class="required">*</span></label>
                  <div>
                   <%= f.text_field :username, class: "form-control"%>
                  </div>
                </fieldset>
                  <br />
                 <fieldset>
                  <label>Email <span class="required">*</span></label>
                  <div>
                   <%= f.text_field :email, class: "form-control"%>
                  </div>
                </fieldset>
                <br />
                <fieldset>
                  <label>Contraseña<span class="required"></span></label>
                  <div>
                 <%= f.password_field :password, autocomplete: "off", class: "form-control" %></div>
                </fieldset>
                <br />
                 <fieldset>
                  <label>Representante Legal <span class="required"></span></label>
                  <div>
                   <%= f.text_field :manager, class: "form-control"%>
                  </div>
                </fieldset>
                <br />
                <fieldset>
                  <label> Descripción <span class="required"></span></label>
                  <div>
                   <%= f.text_field :description, class: "form-control"%>
                  </div>
                </fieldset>
                <br />
                <fieldset>
                  <label>Sitio Web <span class="required"></span></label>
                  <div>
                   <%= f.text_field :website, class: "form-control"%>
                  </div>
                </fieldset>
                <br />
                <fieldset>
                  <br />

                 <fieldset>
                  <div class="field">
                    <%= f.label :country, "País" %><br />
                   <select name="institution[country]">
                    <option value = "Colombia">Colombia</option>
                   </select>
                  </div>
                </fieldset>
                  <br />

<fieldset>
  <div class="field">
    <%= f.label :region, "Región" %><br />
    <select name="institution[region]">
      <option value = "Amazonas">Amazonas</option>
      <option value = "Antioquia">Antioquia</option>
      <option value = "Arauca">Arauca</option>
      <option value = "Atlántico">Atlántico</option>
      <option value = "Bolívar">Bolívar</option>
      <option value = "Boyacá">Boyacá</option>
      <option value = "Caldas">Caldas</option>
      <option value = "Caquetá">Caquetá</option>
      <option value = "Casanare">Casanare</option>
      <option value = "Cauca">Cauca</option>
      <option value = "Cesar">Cesar</option>
      <option value = "Chocó">Chocó</option>
      <option value = "Córdoba">Córdoba</option>
      <option value = "Cundinamarca">Cundinamarca</option>
      <option value = "Guainía">Guainía</option>
      <option value = "Guaviare">Guaviare</option>
      <option value = "Huila">Huila</option>
      <option value = "La Guajira">La Guajira</option>
      <option value = "Magdalena">Magdalena</option>
      <option value = "Meta">Meta</option>
      <option value = "Nariño">Nariño</option>
      <option value = "Norte de Santander">Norte de Santander</option>
      <option value = "Putumayo">Putumayo</option>
      <option value = "Quindío">Quindío</option>
      <option value = "Risaralda">Risaralda</option>
      <option value = "San Andrés y Providencia">San Andrés y Providencia</option>
      <option value = "Santander">Santander</option>
      <option value = "Sucre">Sucre</option>
      <option value = "Tolima">Tolima</option>
      <option value = "Valle del Cauca">Valle del Cauca</option>
      <option value = "Vaupés">Vaupés</option>
      <option value = "Vichada">Vichada</option>
    </select>
  </div>
</fieldset>
<br />

<fieldset>
  <div class="field">
    <%= f.label :city, "Ciudad" %><br />
    <select name="institution[city]">
      <option value = "Arauca">Arauca</option>
      <option value = "Armenia">Armenia</option>
      <option value = "Barranquilla">Barranquilla</option>
      <option value = "Bogotá">Bogotá</option>
      <option value = "Bucaramanga">Bucaramanga</option>
      <option value = "Cali">Cali</option>
      <option value = "Cartagena de Indias">Cartagena de Indias</option>
      <option value = "Cucutá">Cucutá</option>
      <option value = "Florencia">Florencia</option>
      <option value = "Ibagué">Ibagué</option>
      <option value = "Inírida">Inírida</option>
      <option value = "Leticia">Leticia</option>
      <option value = "Manizalez">Manizalez</option>
      <option value = "Medellín">Medellín</option>
      <option value = "Mitú">Mitú</option>
      <option value = "Mocoa">Mocoa</option>
      <option value = "Montería">Montería</option>
      <option value = "Neiva">Neiva</option>
      <option value = "Pasto">Pasto</option>
      <option value = "Pereira">Pereira</option>
      <option value = "Popayán">Popayán</option>
      <option value = "Puerto Carreño">Puerto Carreño</option>
      <option value = "Quibdó">Quibdó</option>
      <option value = "Riohacha">Riohacha</option>
      <option value = "San Andrés">San Andrés</option>
      <option value = "San José del Guaviare">San José del Guaviare</option>
      <option value = "Santa Marta">Santa Marta</option>
      <option value = "Sincelejo">Sincelejo</option>
      <option value = "Tunja">Tunja</option>
      <option value = "Valledupar">Valledupar</option>
      <option value = "Villavicencio">Villavicencio</option>
      <option value = "Yopal">Yopal</option>
    </select>
  </div>
</fieldset>
<br />

<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>


        <div class="field account-sign-in">
                    <p>
                      

                      <%= f.submit "Crear Institución", class: 'btn btn-primary btn-sm' %>

                    </p>

                    
                  </div>

<% end %>


<%= link_to 'Atrás', admin_institutions_path %>

   </div>
          </div>

        </div>
      </section>
      <!-- Page Content / End -->

app/views/admin/institutions/show.html.erb
<section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h1>Fundaciones</h1>
            </div>
            <div class="col-md-6">
              <ul class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li><a href="#">Pages</a></li>
                <li class="active">Team Member</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Heading / End -->

<section class="page-content">
        <div class="container">

          <div class="row">
            <div class="col-md-5">
              <figure class="alignnone">
                <img src="http://placehold.it/470x470" alt="">
              </figure>
            </div>
            <div class="col-md-7">
              <div class="spacer visible-sm visible-xs"></div>
              <div class="team-single-head">
                <h2><%= @admin_institution.name %><small>/
                 <%= @admin_institution.manager %></small></h2>
              </div>
              <h5>Short Info</h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu nisi ac mi malesuada vestibulum. Phasellus tempor nunc eleifend cursus molestie. Mauris lectus arcu, pellentesque at sodales sit amet, condimentum id nunc. Aliquam tincidunt a sapien nec faucibus. Maecenas tempus quam at pellentesque laoreet. Fusce ullamcorper est a ultricies vestibulum. Nullam vitae ultrices sapien.</p>

              <p>Donec ornare mattis suscipit. Praesent fermentum accumsan vulputate. Sed velit nulla, sagittis non erat id, dictum vestibulum ligula. Maecenas sed enim sem. Etiam</p>

              <h5>Profile</h5>

              <dl class="dl-horizontal">
                <dt>Email</dt>
                <dd><a href="#"><%= @admin_institution.email %></a></dd>
                <dt>Website</dt>
                <dd><a href="#"> <%= @admin_institution.website %></a></dd>
                <dt>País</dt>
                <dd><%= @admin_institution.country %>
                    <%= @admin_institution.region %>
                    <%= @admin_institution.city %></dd>
              </dl>
            </div>
          </div>
                 

<%= link_to 'Editar', edit_admin_institution_path(@institution) %> |
<%= link_to 'Atrás', admin_institutions_path %>
           </div>
            </section>


<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @admin_institution.name %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @admin_institution.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_institution.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin_institution.password %>
</p>

<p>
  <strong>Ubicación:</strong>
  <%= @admin_institution.country %>
  <%= @admin_institution.region %>
  <%= @admin_institution.city %>
</p>

<p>
  <strong>Representante Legal:</strong>
  <%= @admin_institution.manager %>
</p>

<p>
  <strong>Website:</strong>
  <%= @admin_institution.website %>
</p>
<p>
  <strong>País</strong>
<%= @admin_institution.country %>
</p>

  