config/routes.rb
Micropost::Application.routes.draw do
  get "home/index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/faq"
  get "static_pages/services"
  get "static_pages/blog"
  get "static_pages/blog_post"

  namespace :admin do
    resources :pets

  end

   namespace :admin do
    resources :institutions
  end

  namespace :admin do
    resources :posts
  end

  resources :pets

  resources :institutions

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :posts

  resources :users
  root 'home#index'

  get 'tags/:tag', to: 'pets#index', as: :tag
    resources :pets do
     collection do
     get :search

    end   
 end

resources :pet do
  collection do
    match 'search' => 'pet#search', via: [:get, :post], as: :search
  end
end

end

app/models/pet.rb
class Pet < ActiveRecord::Base

  has_attached_file :photo, :styles => { :large => "708x671#", :medium => "320x290#", :mediumsmall => "259x159#",  :small => "288x268#", :thumb => "160x160#" },
                  :storage => :s3,
                  :bucket => 'adoptame-pets-photos'

  validates_attachment_content_type :photo, :presence => true, :size => { :in => 0..10.megabytes }, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :institution
  has_one :institution
  belongs_to :institution

accepts_nested_attributes_for :institution

	acts_as_taggable

	def self.search(search)
  	if search
   			 find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
 		 else
   			 find(:all)
  	end
	end

end

app/controllers/admin/pets_controller.rb
class Admin::PetsController < ApplicationController
  before_action :set_admin_pet, only: [:show, :edit, :update, :destroy]

  # GET /admin/pets
  # GET /admin/pets.json
  def index
    @admin_pets = Pet.all
  end

  # GET /admin/pets/1
  # GET /admin/pets/1.json
  def show
  end

  # GET /admin/pets/new
  def new
    @admin_pet = Pet.new
  end

  # GET /admin/pets/1/edit
  def edit
  end

  # POST /admin/pets
  # POST /admin/pets.json
  def create
    @admin_pet = Pet.new(admin_pet_params)

    respond_to do |format|
      if @admin_pet.save
        format.html { redirect_to @admin_pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/pets/1
  # PATCH/PUT /admin/pets/1.json
  def update
    respond_to do |format|
      if @admin_pet.update(admin_pet_params)
        format.html { redirect_to @admin_pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/pets/1
  # DELETE /admin/pets/1.json
  def destroy
    @admin_pet.destroy
    respond_to do |format|
      format.html { redirect_to admin_pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_pet
      @admin_pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_pet_params
      params.require(:admin_pet).permit(:name, :age, :kind, :gender, :size, :story, :city, :country, :region, :user_id, :institution_id, :manager, :photo,:tag_list)
    
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  

  # GET /pets
  # GET /pets.json
  def index
   
      # @pets = Pet.all
      # if params[:tag]
      #   @pets = Pet.tagged_with(params[:tag])
      # else
      #   @pets = Pet.all
      # end

      # def index
      # @search = Pet.search(params[:q])
      # @pets = @search.result
      # end

      @search = Pet.ransack(params[:q])
      @pets = @search.result
      @institution = Institution.all
        
  
  end

   

  # GET /pets/1
  # GET /pets/1.json
  def show


  end

  # GET admin/pets/new
  def new
    @pet = Pet.new
    @institution = Institution.all
  end

  # GET admin/pets/1/edit
  def edit
  end

  # POST admin/pets
  # POST admin/pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @admin_pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT admin/pets/1
  # PATCH/PUT admin/pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @admin_pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE admin/pets/1
  # DELETE admin/pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to admin_pets_url }
      format.json { head :no_content }
    end
  end

def preview
  @photo = Pet_photo.find(params[:id])
   if @photo.contenttype == "image"          
      img_orig = Magick::Image.read("/assets/images/"+@photo.filename).first
      img = img_orig.resize_to_fit(200,200)
      img = img.vignette(x, y, radius=0.0, sigma=10.0)
     @response.headers["Content-type"] = img.mime_type
      render :text => img.to_blob    
   end
end

 def search
    @pets = Pet.tagged_with(params[:search])
    
    if @pets.empty?
      redirect_to home_index_path, alert: 'No se encontraron restaurantes con los criterios de busqueda ingresados. Por favor intente con otra palabra.' 
    end
  end


private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :age, :kind, :gender, :size, :story, :city, :country, :region, :user_id, :institution_id, :manager, :photo,:tag_list)
    end
end

app/helpers/admin/pets_helper.rb
module Admin::PetsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/admin/pets/_form.html.erb
<%= form_for(@admin_pet) do |f| %>

     <% if @admin_pet.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(@admin_pet.errors.count, "error") %> prohibited this admin_pet from being saved:</h2>

            <ul>
            <% @admin_pet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
            </div>
    <% end %>

          <div class="field">
            <%= f.label :photo %><br />
            <%= f.file_field :photo %>
          </div>

          <div class="field">
            <%= f.label :name, "Nombre" %><br />
            <%= f.text_field :name %>
          </div>
            <br />

          <div class="field">
             <%= f.label :age, "Edad" %><br />
             <%= f.number_field(:age, in: 1..360) %> Meses 
             <%= f.label :age, "Edad en meses. Ejemplo 13" %>
          </div>   
            <br />

            <br />

          <div class="field">
            <%= f.label :kind, "Tipo" %><br />
            <%= f.radio_button("kind", "Perro") %> <%= f.label :kind_perro, "Perro" %> <br />
            <%= f.radio_button("kind", "Gato") %>  <%= f.label :kind_perro, "Gato" %>
            <!--   <input type="radio" name="kind" value="Perro">Perro<br />
            <input type="radio" name="kind" value="Gato">Gato -->
          </div>
            <br />

          <div class="field">
            <%= f.label :gender, "Género" %><br />
            <%= f.radio_button("gender", "Macho") %> <%= f.label :gender_macho, "Macho" %> <br />
            <%= f.radio_button("gender", "Hembra") %>  <%= f.label :gender_hembra, "Hembra" %>
          </div>
            <br />

          <div class="field">
            <%= f.label :size, "Tamaño" %><br />
            <%= f.radio_button("size", "Pequeño") %> <%= f.label :size_pequeño, "Pequeño" %> <br />
            <%= f.radio_button("size", "Mediano") %> <%= f.label :size_mediano, "Mediano" %> <br />
            <%= f.radio_button("size", "Grande") %> <%= f.label  :size_grande, "Grande" %> <br />
            <%= f.radio_button("size", "Extra Grande") %>  <%= f.label :size_extragrande, "Extra Grande" %>
          </div>  
            <br />  

          <div class="field">
            <%= f.label :region, "Región" %> <br />
            <select name="pet[region]">
            <option value = "Amazonas">Amazonas</option>
            <option value = "Antioquia">Antioquia</option>
            <option value = "Arauca">Arauca</option>
            <option value = "Atlántico">Atlántico</option>
            <option value = "Bolívar">Bolívar</option>
            <option value = "Boyacá">Boyacá</option>
            <option value = "Caldas">Caldas</option>
            <option value = "Caquetá">Caquetá</option>
            <option value = "Casanare">Casanare</option>
            <option value = "Cauca">Cauca</option>
            <option value = "Cesar">Cesar</option>
            <option value = "Chocó">Chocó</option>
            <option value = "Córdoba">Córdoba</option>
            <option value = "Cundinamarca">Cundinamarca</option>
            <option value = "Guainía">Guainía</option>
            <option value = "Guaviare">Guaviare</option>
            <option value = "Huila">Huila</option>
            <option value = "La Guajira">La Guajira</option>
            <option value = "Magdalena">Magdalena</option>
            <option value = "Meta">Meta</option>
            <option value = "Nariño">Nariño</option>
            <option value = "Norte de Santander">Norte de Santander</option>
            <option value = "Putumayo">Putumayo</option>
            <option value = "Quindío">Quindío</option>
            <option value = "Risaralda">Risaralda</option>
            <option value = "San Andrés y Providencia">San Andrés y Providencia</option>
            <option value = "Santander">Santander</option>
            <option value = "Sucre">Sucre</option>
            <option value = "Tolima">Tolima</option>
            <option value = "Valle del Cauca">Valle del Cauca</option>
            <option value = "Vaupés">Vaupés</option>
            <option value = "Vichada">Vichada</option>
            </select>
         </div>
            <br />

         <div class="field">
            <%= f.label :city, "Ciudad" %> <br />
          <select name="pet[city]">
            <option value = "Arauca">Arauca</option>
            <option value = "Armenia">Armenia</option>
            <option value = "Barranquilla">Barranquilla</option>
            <option value = "Bogotá">Bogotá</option>
            <option value = "Bucaramanga">Bucaramanga</option>
            <option value = "Cali">Cali</option>
            <option value = "Cartagena de Indias">Cartagena de Indias</option>
            <option value = "Cucutá">Cucutá</option>
            <option value = "Florencia">Florencia</option>
            <option value = "Ibagué">Ibagué</option>
            <option value = "Inírida">Inírida</option>
            <option value = "Leticia">Leticia</option>
            <option value = "Manizalez">Manizalez</option>
            <option value = "Medellín">Medellín</option>
            <option value = "Mitú">Mitú</option>
            <option value = "Mocoa">Mocoa</option>
            <option value = "Montería">Montería</option>
            <option value = "Neiva">Neiva</option>
            <option value = "Pasto">Pasto</option>
            <option value = "Pereira">Pereira</option>
            <option value = "Popayán">Popayán</option>
            <option value = "Puerto Carreño">Puerto Carreño</option>
            <option value = "Quibdó">Quibdó</option>
            <option value = "Riohacha">Riohacha</option>
            <option value = "San Andrés">San Andrés</option>
            <option value = "San José del Guaviare">San José del Guaviare</option>
            <option value = "Santa Marta">Santa Marta</option>
            <option value = "Sincelejo">Sincelejo</option>
            <option value = "Tunja">Tunja</option>
            <option value = "Valledupar">Valledupar</option>
            <option value = "Villavicencio">Villavicencio</option>
            <option value = "Yopal">Yopal</option>
          </select>
        </div>
            <br />


          <div class="field">
            <%= f.label :story, "Historia o Descripción" %><br />
            <%= f.text_area :story, size: "60x3", maxlength: "200" %>
            <!-- <textarea name="comments" rows="3" maxlength="200" cols="60"></textarea> -->
          </div>

          <div class="field">
            <%= f.label :institution_id %><br>
            <%= f.select :institution_id, options_for_select(@institutions) %>
          </div>

          <div class="field">
            <%= f.label :tag_list, "Tags (separated by commas)" %><br />
            <%= f.text_field :tag_list %>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>
<% end %>

app/views/admin/pets/index.html.erb
<div class="main" role="main">

      <!-- Page Heading -->
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h1>Administrador de Mascotas</h1>
            </div>
            <div class="col-md-6">
              <ul class="breadcrumb">
                <li><a href="/">Inicio</a></li>
                <li><a href="about">¿Quiénes Somos?</a></li>
                <li class="active">Administrador de Mascotas</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Heading / End -->

      <!-- Page Content -->
      <section class="page-content">
        <div class="container">

            <div class="table-responsive">
              <table class="job-manager-jobs table table-bordered table-striped">
                <thead>
                  <tr>
                   <th>Nombre</th>
      <th>Edad</th>
      <th>Tipo</th>
      <th>Género</th>
      <th>Tamaño</th>
      <th>Historia o descripción</th>
      <th>Región</th>
      <th>Ciudad</th>
      <th>País</th>
      <th>Institución</th>
      <th>Tags</th>

                  </tr>
                </thead>
                <tbody>
               
    <% @admin_pets.each do |admin_pet| %>
      <tr>
        <td><%= admin_pet.name %></td>
        <td><%= admin_pet.age %></td>
        <td><%= admin_pet.kind %></td>
        <td><%= admin_pet.gender %></td>
        <td><%= admin_pet.size %></td>
        <td><%= admin_pet.story %></td>
        <td><%= admin_pet.region %></td>
        <td><%= admin_pet.city %></td>
        <td><%= admin_pet.country %></td>
        <td><%= admin_pet.institution %></td>
        <td><%= admin_pet.tag_list %></td>



      
        <td><%= link_to 'Mostrar', admin_pet %></td>
        <td><%= link_to 'Editar', edit_admin_pet_path(admin_pet) %></td>
        <td><%= link_to 'Destruir', admin_pet, method: :delete, data: { confirm: 'Esta seguro?' } %></td>

      </tr>
    <% end %>
  </tbody>
              </table>

              

              
<%= link_to 'Nueva Mascota', new_admin_pet_path %>
            </div>

          </div>

        </div>
      </section>




<br>

app/views/admin/pets/new.html.erb
 <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <h1>Nueva Mascota</h1>
            </div>
            <div class="col-md-6">
              <ul class="breadcrumb">
                <li><a href="/">Inicio</a></li>
                <li><a href="about">¿Quiénes Somos?</a></li>
                <li class="active">Nueva Mascota</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Heading / End -->
<!-- Page Content -->
      <section class="page-content">
        <div class="container">

<%= form_for(@admin_pet) do |f| %>
  <% if @admin_pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_pet.errors.count, "error") %> prohibited this admin_pet from being saved:</h2>

      <ul>
      <% @admin_pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :photo %><br />
  <%= f.file_field :photo %>
</div>

  <div class="field">
    <%= f.label :name, "Nombre" %><br />
    <%= f.text_field :name %>
  </div>
<br />

 <div class="field">
    <%= f.label :age, "Edad" %><br />
    <%= f.number_field(:age, in: 1..300) %> <%= f.label :age, "Meses" %><br />
    Por favor diligenciar este campo en meses. Ejemplo "48" meses = 4 años
<br />
<br />
   
 <div class="field">
    <%= f.label :kind, "Tipo" %><br />
    <%= f.radio_button("kind", "Perro") %> <%= f.label :kind_perro, "Perro" %> <br />
    <%= f.radio_button("kind", "Gato") %>  <%= f.label :kind_perro, "Gato" %>
  <!--   <input type="radio" name="kind" value="Perro">Perro<br />
    <input type="radio" name="kind" value="Gato">Gato -->
  </div>
<br />

  <div class="field">
    <%= f.label :gender, "Género" %><br />
    <%= f.radio_button("gender", "Macho") %> <%= f.label :gender_macho, "Macho" %> <br />
    <%= f.radio_button("gender", "Hembra") %>  <%= f.label :gender_hembra, "Hembra" %>
  </div>
  <br />

  <div class="field">
    <%= f.label :size, "Tamaño" %><br />
     <%= f.radio_button("size", "Pequeño") %> <%= f.label :size_pequeño, "Pequeño" %> <br />
     <%= f.radio_button("size", "Mediano") %> <%= f.label :size_mediano, "Mediano" %> <br />
     <%= f.radio_button("size", "Grande") %> <%= f.label  :size_grande, "Grande" %> <br />
     <%= f.radio_button("size", "Extra Grande") %>  <%= f.label :size_extragrande, "Extra Grande" %>
   </div>  
<br />  


  <div class="field">
    <%= f.label :country, "País" %><br />
   <select name="pet[country]">
    <option value = "Colombia">Colombia</option>
   </select>
  </div>
<br />

  <div class="field">
    <%= f.label :region, "Región" %><br />
    <select name="pet[region]">
      <option value = "Amazonas">Amazonas</option>
      <option value = "Antioquia">Antioquia</option>
      <option value = "Arauca">Arauca</option>
      <option value = "Atlántico">Atlántico</option>
      <option value = "Bolívar">Bolívar</option>
      <option value = "Boyacá">Boyacá</option>
      <option value = "Caldas">Caldas</option>
      <option value = "Caquetá">Caquetá</option>
      <option value = "Casanare">Casanare</option>
      <option value = "Cauca">Cauca</option>
      <option value = "Cesar">Cesar</option>
      <option value = "Chocó">Chocó</option>
      <option value = "Córdoba">Córdoba</option>
      <option value = "Cundinamarca">Cundinamarca</option>
      <option value = "Guainía">Guainía</option>
      <option value = "Guaviare">Guaviare</option>
      <option value = "Huila">Huila</option>
      <option value = "La Guajira">La Guajira</option>
      <option value = "Magdalena">Magdalena</option>
      <option value = "Meta">Meta</option>
      <option value = "Nariño">Nariño</option>
      <option value = "Norte de Santander">Norte de Santander</option>
      <option value = "Putumayo">Putumayo</option>
      <option value = "Quindío">Quindío</option>
      <option value = "Risaralda">Risaralda</option>
      <option value = "San Andrés y Providencia">San Andrés y Providencia</option>
      <option value = "Santander">Santander</option>
      <option value = "Sucre">Sucre</option>
      <option value = "Tolima">Tolima</option>
      <option value = "Valle del Cauca">Valle del Cauca</option>
      <option value = "Vaupés">Vaupés</option>
      <option value = "Vichada">Vichada</option>
    </select>
  </div>
<br />

  <div class="field">
    <%= f.label :city, "Ciudad" %><br />
    <select name="pet[city]">
      <option value = "Arauca">Arauca</option>
      <option value = "Armenia">Armenia</option>
      <option value = "Barranquilla">Barranquilla</option>
      <option value = "Bogotá">Bogotá</option>
      <option value = "Bucaramanga">Bucaramanga</option>
      <option value = "Cali">Cali</option>
      <option value = "Cartagena de Indias">Cartagena de Indias</option>
      <option value = "Cucutá">Cucutá</option>
      <option value = "Florencia">Florencia</option>
      <option value = "Ibagué">Ibagué</option>
      <option value = "Inírida">Inírida</option>
      <option value = "Leticia">Leticia</option>
      <option value = "Manizalez">Manizalez</option>
      <option value = "Medellín">Medellín</option>
      <option value = "Mitú">Mitú</option>
      <option value = "Mocoa">Mocoa</option>
      <option value = "Montería">Montería</option>
      <option value = "Neiva">Neiva</option>
      <option value = "Pasto">Pasto</option>
      <option value = "Pereira">Pereira</option>
      <option value = "Popayán">Popayán</option>
      <option value = "Puerto Carreño">Puerto Carreño</option>
      <option value = "Quibdó">Quibdó</option>
      <option value = "Riohacha">Riohacha</option>
      <option value = "San Andrés">San Andrés</option>
      <option value = "San José del Guaviare">San José del Guaviare</option>
      <option value = "Santa Marta">Santa Marta</option>
      <option value = "Sincelejo">Sincelejo</option>
      <option value = "Tunja">Tunja</option>
      <option value = "Valledupar">Valledupar</option>
      <option value = "Villavicencio">Villavicencio</option>
      <option value = "Yopal">Yopal</option>
    </select>
  </div>
<br />

 <!-- <div class="field">
    <%#= f.label :user_id %><br>
    <%#= f.text_field :user_id %>
  </div> -->

 <div class="field">
    <%= f.label :institution, "Institución" %><br />
     <select name="pet[institution]">
    <%= f.text_field :institution, size: "60x1", maxlength: "200" %>
  </div>


  <div class="field">
    <%= f.label :story, "Historia o Descripción" %><br />
    <%= f.text_area :story, size: "60x3", maxlength: "200" %>
    <!-- <textarea name="comments" rows="3" maxlength="200" cols="60"></textarea> -->
  </div>

   <div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>

  <div class="actions">
    <%= f.submit "Crear Mascota" %>
  </div>

<% end %>



<%= link_to 'Atrás', admin_pets_path %>

</div>
</section	>

app/views/admin/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @admin_pet.age%> Meses
</p>

<p>
  <strong>Kind:</strong>
  <%= @admin_pet.kind %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @admin_pet.gender %>
</p>

<p>
  <strong>Size:</strong>
  <%= @admin_pet.size %>
</p>

<p>
  <strong>Story:</strong>
  <%= @admin_pet.story %>
</p>

<p>
  <strong>Region:</strong>
  <%= @admin_pet.region %>
</p>

<p>
  <strong>City:</strong>
  <%= @admin_pet.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @admin_pet.country %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @admin_pet.institution_id %>
</p>

<%= link_to 'Editar', edit_admin_pet_path(@admin_pet) %> |
<%= link_to 'Atrás', admin_pets_path %>